name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      run: rustup toolchain install nightly --no-self-update --profile minimal --target thumbv7em-none-eabihf

    - name: Generate docs
      run: cargo +nightly rustdoc --target thumbv7em-none-eabihf -- --cfg docsrs

    - name: Write redirect
      run: echo "<meta http-equiv=\"refresh\" content=\"0;url=imxrt_boot_gen\">" > target/thumbv7em-none-eabihf/doc/index.html

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/thumbv7em-none-eabihf/doc
        publish_branch: gh-pages
