name: All Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --no-self-update --profile minimal --target thumbv7em-none-eabihf
    - name: Build everything for the host
      run: cargo build --workspace
    - name: Run all tests on the host
      run: cargo test --workspace
    - name: Build everything for some embedded target
      run: cargo build --workspace --target=thumbv7em-none-eabihf
  
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --no-self-update --profile minimal --component clippy --target thumbv7em-none-eabihf
      - run: cargo clippy --workspace --target=thumbv7em-none-eabihf -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --no-self-update --profile minimal --component rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
