name: All Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        feature: ["imxrt1010", "imxrt1020", "imxrt1040", "imxrt1050", "imxrt1060", "imxrt1064", "imxrt1170", "imxrt1180"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (${{ matrix.feature }})
      run: cargo build --package=imxrt-boot-gen --verbose --features=${{ matrix.feature }}
    - name: Run tests (${{ matrix.feature }})
      run: cargo test --package=imxrt-boot-gen --verbose --features=${{ matrix.feature }}
  
  clippy:
    strategy:
      matrix:
        feature: ["imxrt1010", "imxrt1020", "imxrt1040", "imxrt1050", "imxrt1060", "imxrt1170", "imxrt1180"]
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --package=imxrt-boot-gen --features=${{ matrix.feature }} -- -D warnings
          name: Run clippy (${{ matrix.feature }})

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  fcbs:
    strategy:
      matrix:
        fcb: ["imxrt1010evk-fcb", "imxrt1060evk-fcb", "imxrt1170evk-fcb", "imxrt1180evk-fcb"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7em-none-eabihf
    - name: Build for an embedded target
      run: cargo build --package=${{ matrix.fcb }} --verbose --target=thumbv7em-none-eabihf
    - name: Build and run tests on the host
      run: cargo test --package=${{ matrix.fcb }} --verbose
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --package=${{ matrix.fcb }} -- -D warnings
        name: Lint the package
